### ISSUE TITLE
Interested in contributing

### ISSUE THREAD

**Issue by marc2332** [mlajtos/mosaic#7]
Hello!

I just found mosaic... and I am pretty amazed by the idea!

Is there any Discord server for it?

I would like to contribute, I have experience with Electron and a bit with React 😄 👍🏻

**Comment by AlphaRacer** [comment]
Hello!

Even I'd like to contribute, I have experience in JS, CSS and Electron!

**Comment by mlajtos** [comment]
Hello marc2332 and welcome 🙂 

Currently the is no Discord server. However, you are free to create it. I was hoping that [Github Discussions](https://docs.github.com/en/github/building-a-strong-community/about-team-discussions) would be out of beta by now, but not yet.

---

About the contribution – main short-term focus is to get Mosaic into state where one can use it as a casual daily driver. There are 3 obvious showstoppers:

1. **Shortcuts for keyboard users**, e.g. it is not obvious what tab to close when you press <kbd>Ctrl-W</kbd> (<kbd>⌘W</kbd>) in split-screen
2. **Small tweaks for mouse users**, e.g. there is no button for a new tab, click on dock icons doesn't do anything
3. **Ability to use Google services** – right now you are not able to login into Google products <sup id="a1">[1](#f1)</sup> because it detects that the app is an Electron app.

Having these covered, we can use Mosaic on a daily basis, and the closed feedback loop will yield next targets.

Of course, this is my view – the best course of action for you is to download it, try it out and see for yourself what bothers you. There is a lot to be done!

---

<sup id="f1">1</sup> Using Google Meet in split-screen is one of the use cases where Mosaic can really shine.

**Comment by mlajtos** [comment]
Hey @marc2332, checkout #8 which is a good first issue.

**Comment by marc2332** [comment]
About the Discord server, I think it would be great to have one since it allows a more direct communication with the users and the devs.

Also, I have some some thoughts about mosaic:

1. The titlebar is not showing in Windows 
![imagen](https://user-images.githubusercontent.com/38158676/90051642-482a4d80-dcd8-11ea-8328-91d89eaf6af4.png)

    I don't know if that's intended but in your screenshot in the readme it shows the traffic lights of MacOS
2. The ctrl+w shortcut doesn't close any tab, it just closes the entire app

But all the other looks so cool! I am going to take a look at the Finding text issue 👍🏻 😄

**Comment by marc2332** [comment]
Also, I see no reasons to always maximize the window when opening. https://github.com/mlajtos/mosaic/blob/64107ac344cf3f30124a2a1864c1875cbb6c04b3/src/main/index.js#L31

I would suggest using something like electron-window-state https://www.npmjs.com/package/electron-window-state to preserve the window position and size after closing

**Comment by mlajtos** [comment]
I converted your suggestions into issues. Closing this one.
